version: "3.9"

services:
  fastapi_app:
    build:
      context: ./app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8000 | grep 200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  streamlit_app:
    build:
      context: ./streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8501 | grep 200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  tester:
    image: curlimages/curl:latest
    container_name: tester
    depends_on:
      fastapi_app:
        condition: service_healthy
      streamlit_app:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: |
      echo "Waiting for FastAPI...";
      for i in $$(seq 1 10); do
        if curl -s http://fastapi_app:8000/ > /dev/null; then
          echo "✅ FastAPI is up!";
          break;
        fi;
        echo "⏳ Retrying FastAPI in 5s... ($$i)";
        sleep 5;
      done;

      echo "Waiting for Streamlit...";
      for i in $$(seq 1 10); do
        if curl -s http://streamlit_app:8501/ > /dev/null; then
          echo "✅ Streamlit is up!";
          break;
        fi;
        echo "⏳ Retrying Streamlit in 5s... ($$i)";
        sleep 5;
      done;

      echo "✅ Tester Done Successfully!";
